### ISSUE TITLE
how to connect the network 

### ISSUE THREAD

**Issue by sivanagarajumolabant** [8468/bitboot#3]
can you please tell me the both systems should run on different networks or same network(LAN)?
 should i run both machines with the same magic name ?
what are the settings i have to do in my system?

**Comment by bmuller** [comment]
This is not the right forum for general networking advice (github issues are for bugs, not general usage questions).  That said - I'll add to the many answers found on #2 - you cannot use bitboot to find multiple nodes all hiding behind the same NAT router.  Bitboot is only useful for finding other nodes with different IP addresses on the internet (since the DHT used is internet based and all nodes are internet addressable), *not* finding other nodes on a LAN.
